language: node_js
node_js:
  - 'node'

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: false
  local_dir: dist
  target_branch: master
  github_token: $GITHUB_TOKEN
  email: 'naveenrohilla99@gmail.com'
  name: 'Naveen Rohilla'
  commit_message: 'Deploy'
  on:
    branch: development
